name: Build all plugins
on: pull_request
concurrency:
  group: build-all-${{ github.ref }}
  cancel-in-progress: true
jobs:
  directories:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v3
      - id: set-dirs
        # get all dirs inside the examples with a plugin json that is not inside node_modules
        run: echo "dir=$(echo $(find examples "$@" -iname 'package.json' -not -path '*/node_modules/*' -exec dirname {} \;) | jq -R -s -c 'split(" ")[:-1]')" >> $GITHUB_OUTPUT
  build_all:
    runs-on: ubuntu-latest
    needs: [directories]
    strategy:
      matrix:
        dir: ${{fromJson(needs.directories.outputs.dir)}}
    defaults:
      run:
        working-directory: ${{matrix.dir}}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies for ${{matrix.dir}}
        run: yarn install
      - name: Build example ${{matrix.dir}}
        run: yarn build
