name: Build all plugins
on: pull_request
concurrency:
  group: build-all-${{ github.ref }}
  cancel-in-progress: true
jobs:
  directories:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3
      - id: set-dirs
        # get all dirs inside the examples with a plugin json that is not inside node_modules
        run: echo "dir=$(echo $(find examples "$@" -iname 'package.json' -not -path '*/node_modules/*' -exec dirname {} \;) | jq -R -s -c 'split(" ")[:-1]')" >> $GITHUB_OUTPUT
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
    
  build_all:
    runs-on: ubuntu-latest
    needs: [directories]
    strategy:
      matrix:
        dir: ${{fromJson(needs.directories.outputs.dir)}}
    defaults:
      run:
        working-directory: ${{matrix.dir}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies for ${{matrix.dir}}
        run: yarn install --immutable --prefer-offline
      - name: Build example ${{matrix.dir}}
        run: yarn build
  notify:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [build_all]
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        if: contains(fromJson('["failure"]'), needs.build_all.result)
        with:
            channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
            payload: |
              {                
                "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": ":blob-sad: Plugin Examples build step ${{ needs.build_all.result }} on `${{ github.head_ref || github.ref_name }}`"
                        }
                      },
                      {
                        "type": "actions",
                        "elements": [
                          {
                            "type": "button",
                            "text": {
                              "type": "plain_text",
                              "text": ":octocat: Open Job",
                              "emoji": true
                            },
                            "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                            "action_id": "actionId-0"
                          },
                          {
                            "type": "button",
                            "text": {
                              "type": "plain_text",
                              "text": ":interesting: Commit",
                              "emoji": true
                            },
                            "url": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}",
                            "action_id": "actionId-1"
                          }
                        ]
                      }
                  ]
              }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}        
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK